# Generated by Django 3.2.19 on 2024-02-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Class', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='gallery')),
                ('DOB', models.CharField(max_length=200)),
                ('Guardian', models.CharField(max_length=200)),
            ],
        ),
    ]
